# Generated by Django 3.0.5 on 2020-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_feriado', models.DateField(help_text='Ou dia não útil', unique=True, verbose_name='Feriado')),
                ('descricao', models.TextField(verbose_name='Descrição/Motivo')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_hora_alteracao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
