# Generated by Django 3.0.5 on 2020-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data_feriado',
            field=models.DateField(help_text='Selecione um feriado ou dia não útil no formato: <em>AAAA-MM-DD</em>. ', unique=True, verbose_name='Feriado'),
        ),
    ]
