# Generated by Django 3.0.5 on 2020-04-15 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0002_auto_20200415_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data_feriado',
            field=models.DateField(help_text='Selecione um feriado ou dia não útil no formato: <em>AAAA-MM-DD</em>. ', unique=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='data_hora_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
