# Generated by Django 3.0.5 on 2020-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0003_auto_20200415_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data_hora_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
