# Generated by Django 3.0.5 on 2020-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0004_auto_20200415_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data_feriado',
            field=models.DateField(help_text='Selecione um feriado ou dia não útil no formato: <em>AAAA-MM-DD</em>. ', unique=True, verbose_name='DATA'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='descricao',
            field=models.TextField(verbose_name='DESCRIÇÃO/MOTIVO'),
        ),
    ]
