# Generated by Django 3.0.5 on 2020-04-21 17:36

from django.db import migrations, models
import feriado.models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0005_auto_20200416_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='data_feriado',
            field=models.DateField(help_text='Selecione um feriado ou dia não útil no formato: <em>AAAA-MM-DD</em>. ', unique=True, validators=[feriado.models.validate_weekend], verbose_name='DATA'),
        ),
    ]
